apiVersion: v1
kind: Service
metadata:
  name: capstone
spec:
  selector:
    app: capstone
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      nodePort: 30001
      targetPort: 5000