
Description: EKS cluster

Parameters:
  Project:
    Description: Project name
    Type: String

Resources:
  DetectTextPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "${Project}-capstone-policy"
      PolicyDocument:
        Statement:
        - Effect: Allow
          Action: 
          - "textract:DetectDocumentText"
          Resource: '*'
      Roles:
      - !Ref EKSNodegroupRole
  EKSNodegroupRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      RoleName: !Sub ${Project}-EKS-Nodes-Role
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
  EKSNodegroup:
    Type: 'AWS::EKS::Nodegroup'
    Properties:
      ClusterName: !Sub ${Project}
      NodeRole: !GetAtt EKSNodegroupRole.Arn
      ScalingConfig:
        MinSize: 1
        DesiredSize: 1
        MaxSize: 3
      Labels:
        Project: !Sub ${Project}
        NodeType: Default
      Subnets:
        Fn::Split:
          - ","
          - Fn::ImportValue:
              Fn::Sub: network-Subnets