
Description: EKS cluster

Parameters:
  Project:
    Description: Project name
    Type: String
  EksVersion:
    Description: Version for EKS Cluster
    Type: String
    Default: 1.16

Resources:
  EKSRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - eks.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      RoleName: !Sub ${Project}-EKS-Role
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
  Cluster:
    Type: 'AWS::EKS::Cluster'
    Properties:
      Name: !Sub ${Project}
      Version: !Sub ${EksVersion}
      RoleArn: !GetAtt EKSRole.Arn
      ResourcesVpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue:
              !Sub network-EKS-SG
        SubnetIds:
          Fn::Split:
            - ","
            - Fn::ImportValue:
                Fn::Sub: network-Subnets
